apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    name: books
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8881
  selector:
    name: books
    version: "1.0.0"
  type: NodePort
